# -*- coding: utf-8 -*-
"""lrheaume_lab3_pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy9BcP5sVlsryzHru62LRKrmW061LE7j
"""

#lrheaume_lab3_decision structures
#complete
"""
This module provides functions for calculating discounts and taxes.
It can be used in various pricing scenarios.
"""
def calculate_discount(number_packages):
    package_price = 99
    if number_packages < 10:
        discount = 0
    elif number_packages < 20:
        discount = 0.1
    elif number_packages < 50:
        discount = 0.15
    else:
        discount = 0.2
    return discount * number_packages * package_price
    # Return the amount, not just the discount rate

def main():
    number_packages = float(input("Enter the number of packages purchased: "))
    discount_amount = calculate_discount(number_packages)
    total_price = (number_packages * 99) - discount_amount

    print("") #spacing
    print("Total Price: $", total_price)  # Print the total price
    print("Discount Amount: $", discount_amount)  # Print the discount amount

    print("This discount amount can change if your order quantity changes - let us know if you need an adjustment!")

if __name__ == "__main__":
    main()